export default [
  { path: '/', component: () => import('@/views/Home.vue') },
  { path: '/products', component: () => import('@/views/Products.vue') },
  { path: '/product/:id', component: () => import('@/views/ProductDetail.vue') },
  { path: '/cart', component: () => import('@/views/Cart.vue') },
  { path: '/checkout', component: () => import('@/views/Checkout.vue'), meta: { auth: true } },
  { path: '/order-success', component: () => import('@/views/OrderSuccess.vue'), meta: { auth: true } },
  { path: '/my-orders', component: () => import('@/views/MyOrders.vue'), meta: { auth: true } },
  { path: '/profile', component: () => import('@/views/Profile.vue'), meta: { auth: true } },
  { path: '/wallet', component: () => import('@/views/Wallet.vue'), meta: { auth: true } },
  { path: '/notifications', component: () => import('@/views/Notifications.vue'), meta: { auth: true } },
  { path: '/support', component: () => import('@/views/Support.vue'), meta: { auth: true } },
  { path: '/wishlist', component: () => import('@/views/Wishlist.vue'), meta: { auth: true } },
  { path: '/login', component: () => import('@/views/Login.vue'), meta: { guest: true } },
  { path: '/signup', component: () => import('@/views/Signup.vue'), meta: { guest: true } },
  { path: '/forgot-password', component: () => import('@/views/ForgotPassword.vue'), meta: { guest: true } },
  { path: '/reset-password', component: () => import('@/views/ResetPassword.vue'), meta: { guest: true } },
  { path: '/about', component: () => import('@/views/About.vue') },
  { path: '/contact', component: () => import('@/views/Contact.vue') },
  { path: '/faq', component: () => import('@/views/FAQ.vue') },
  { path: '/privacy', component: () => import('@/views/Privacy.vue') },
  { path: '/terms', component: () => import('@/views/Terms.vue') },
  { path: '/:pathMatch(.*)*', component: () => import('@/views/404.vue') }
]
